const ListaDeProductos = [
    { 
        id: 0, 
        category: "informatica",
        title: "Placa de madre Gigabyte A69HM-E33 V2", 
        description: "Descripcion Prod 1",
        quantity: 0,
        stock: 50, 
        price: 900, 
        pictureUrl: "url a insertar" },
    { 
        id: 1, 
        category: "informatica",
        title: "Procesador A10 7870K 4.0", 
        description: "Descripcion Prod 2", 
        quantity: 0,
        stock: 50,
        price: 300, 
        pictureUrl: "url a insertar" },
    { 
        id: 2, 
        category: "informatica",
        title: "Memoria RAM DRR3 Kingston Hyperx 1866mhz", 
        description: "Descripcion Prod 3", 
        quantity: 0,
        stock: 50,
        price: 600, 
        pictureUrl: "url a insertar" },
    { 
        id: 3, 
        category: "oficina",
        title: "Lámpara", 
        description: "Descripcion Prod Oficina 1", 
        quantity: 0,
        stock: 50,
        price: 900, 
        pictureUrl: "url a insertar" },
    { 
        id: 4, 
        category: "oficina",
        title: "Archivero", 
        description: "Descripcion Prod Oficina 2", 
        quantity: 0,
        stock: 50,
        price: 300, 
        pictureUrl: "url a insertar" },
    { 
        id: 5, 
        category: "oficina",
        title: "Silla de escritorio", 
        description: "Descripcion Prod Oficina3",
        quantity: 0,
        stock: 50, 
        price: 600, 
        pictureUrl: "url a insertar" },
    { 
        id: 6, 
        category: "oficina",
        title: "Escritorio", 
        description: "Descripcion Prod Oficina Oficina", 
        quantity: 0,
        stock: 50,
        price: 1500, 
        pictureUrl: "url a insertar" }
]
export default ListaDeProductos;